import { NextResponse } from 'next/server';
import { getLLMConfig, getDBSettings } from "@/lib/aiConfig";

export const maxDuration = 120; // Allow sufficient time for translation

export async function POST(req: Request) {
  try {
    const { documentContent, targetLanguage } = await req.json();

    if (!documentContent || !targetLanguage) {
      return NextResponse.json({ error: 'Missing documentContent or targetLanguage' }, { status: 400 });
    }

    const dbSettings = await getDBSettings();
    const llmConfig = getLLMConfig(dbSettings);

    if (!llmConfig.apiKey) {
      return NextResponse.json({ error: "API Key not configured" }, { status: 500 });
    }

    const langMap: Record<string, string> = {
      'en': 'English',
      'es': 'Spanish',
      'pt': 'Portuguese (pt-BR)',
    };
    
    const targetLang = langMap[targetLanguage] || targetLanguage;

    const systemPrompt = `You are an expert technical translator. Your task is to translate the provided document into ${targetLang}.
The document may be in Markdown format OR in HTML format (with tags like <h1>, <p>, <strong>, <mark>, etc.).
CRITICAL RULES:
1. Translate the TEXT CONTENT ONLY.
2. DO NOT change ANY formatting — whether Markdown syntax (#, **, *, -, 1., \`, >) or HTML tags/attributes (<h1>, <p>, <strong>, <em>, <mark>, <ul>, <li>, class="...", style="...", data-*).
3. Keep the exact same structure as the original document.
4. Output nothing except the translated document. Do not add conversational text like "Here is your translation...".
5. 100% COMPLETENESS REQUIRED: You MUST translate the ENTIRE document from the very first word to the absolute last word. DO NOT summarize, DO NOT truncate, DO NOT omit any paragraphs, bullet points, or sections, regardless of length.
6. MAXIMUM ACCURACY: Preserve the exact professional tone, technical terminology, and contextual business meaning. Localization must be flawless and native-sounding without losing original intent.`;

    const res = await fetch(llmConfig.baseUrl, {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${llmConfig.apiKey}`,
        ...llmConfig.headers,
      },
      body: JSON.stringify({
        model: llmConfig.model,
        temperature: 0.1, // low temperature for translation stability
        max_tokens: 8192, // Required to strictly prevent large doc truncation
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: documentContent }
        ],
      }),
    });

    if (!res.ok) {
        throw new Error(`LLM Error: ${res.status}`);
    }

    const llmData = await res.json();
    const translatedDocument = llmData.choices?.[0]?.message?.content;

    if (!translatedDocument) {
        throw new Error("No document content generated by LLM");
    }

    return NextResponse.json({ success: true, document: translatedDocument });

  } catch (error) {
    console.error("[DocumentTranslate] Error:", error);
    return NextResponse.json({ error: error instanceof Error ? error.message : String(error) }, { status: 500 });
  }
}
