import { NextResponse } from 'next/server';
import { getLLMConfig, getDBSettings } from "@/lib/aiConfig";

export async function POST(req: Request) {
  try {
    const { documentContent, targetLanguage } = await req.json();

    if (!documentContent || !targetLanguage) {
      return NextResponse.json({ error: 'Missing documentContent or targetLanguage' }, { status: 400 });
    }

    const dbSettings = await getDBSettings();
    const llmConfig = getLLMConfig(dbSettings);

    if (!llmConfig.apiKey) {
      return NextResponse.json({ error: "API Key not configured" }, { status: 500 });
    }

    const langMap: Record<string, string> = {
      'en': 'English',
      'es': 'Spanish',
      'pt': 'Portuguese (pt-BR)',
    };
    
    const targetLang = langMap[targetLanguage] || targetLanguage;

    const systemPrompt = `You are an expert technical translator. Your task is to translate the provided Markdown document into ${targetLang}.
CRITICAL RULES:
1. Translate the TEXT ONLY.
2. DO NOT change ANY markdown formatting, structural elements, headings levels (#), lists (*, -, 1.), bold (**), italics (*), blockquotes (>), or code blocks (\`).
3. Keep the exact same structure as the original document.
4. Output nothing except the translated Markdown. Do not add conversational text like "Here is your translation...".`;

    const res = await fetch(llmConfig.baseUrl, {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${llmConfig.apiKey}`,
        ...llmConfig.headers,
      },
      body: JSON.stringify({
        model: llmConfig.model,
        temperature: 0.1, // low temperature for translation stability
        max_tokens: 6000,
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: documentContent }
        ],
      }),
    });

    if (!res.ok) {
        throw new Error(`LLM Error: ${res.status}`);
    }

    const llmData = await res.json();
    const translatedDocument = llmData.choices?.[0]?.message?.content;

    if (!translatedDocument) {
        throw new Error("No document content generated by LLM");
    }

    return NextResponse.json({ success: true, document: translatedDocument });

  } catch (error) {
    console.error("[DocumentTranslate] Error:", error);
    return NextResponse.json({ error: error instanceof Error ? error.message : String(error) }, { status: 500 });
  }
}
