import { NextResponse } from "next/server";
import { getLLMConfig, getDBSettings } from "@/lib/aiConfig";
import { createServerSupabaseClient } from "@/lib/supabase/server";

export async function POST(
  req: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id: sessionId } = await params;
    const supabase = await createServerSupabaseClient();

    // 1. Fetch the session data
    const { data: session, error: sessionError } = await supabase
      .from('briefing_sessions')
      .select('*, briefing_templates(*)')
      .eq('id', sessionId)
      .single();

    if (sessionError || !session) {
      return NextResponse.json({ error: "Session not found" }, { status: 404 });
    }

    // 2. Prepare data for generation
    const history = session.messages_snapshot || [];
    const briefingState = session.company_info || {};
    const assets = session.final_assets || {};
    const activeTemplate = session.briefing_templates;
    const chosenLanguage = session.chosen_language || 'pt';
    const detectedSignals = session.detected_signals || [];

    const dbSettings = await getDBSettings();
    const llmConfig = getLLMConfig(dbSettings);

    if (!llmConfig.apiKey) {
      return NextResponse.json({ error: "API Key not configured" }, { status: 500 });
    }

    const templateName = activeTemplate?.name || "Briefing Geral";
    const objectives = activeTemplate?.objectives?.join(", ") || "Criar briefing completo do negócio";
    const briefingPurpose = activeTemplate?.briefing_purpose || "";

    const roleLabels: Record<string, { ai: string; client: string }> = {
      en: { ai: 'AI', client: 'Client' },
      es: { ai: 'IA', client: 'Cliente' },
      pt: { ai: 'IA', client: 'Cliente' },
    };
    const roles = roleLabels[chosenLanguage] || roleLabels.pt;

    const conversationTranscript = history.map((m: { role: string; content: string; userAnswer?: string | string[] | number }) => {
      const role = m.role === "assistant" ? roles.ai : roles.client;
      const resp = Array.isArray(m.userAnswer) ? m.userAnswer.join(', ') : m.userAnswer;
      return `[${role}]: ${m.content}${resp ? `\nRespondi: ${resp}` : ""}`;
    }).join("\n\n");

    const langMap: Record<string, string> = {
      'en': 'English',
      'es': 'Spanish',
      'pt': 'Portuguese (pt-BR)',
    };
    const targetLang = langMap[chosenLanguage] || 'Portuguese (pt-BR)';

    interface TranslationLabels {
      role: string;
      langRule: string;
      task: string;
      title: string;
      userMsg: string;
      watermark: string;
    }

    const t_labels: Record<string, TranslationLabels> = {
        pt: {
          role: 'Você é um Estrategista de Marca Sênior e consultor nível McKinsey criando um Documento de Briefing premium.',
          langRule: `REGRA ABSOLUTA DE IDIOMA: Escreva o documento INTEIRO em ${targetLang}.`,
          task: 'TAREFA: Analise TODA a conversa abaixo e produza um documento de briefing completo e estruturado.',
          title: '📋 Briefing Estratégico — [Nome da Empresa]',
          userMsg: 'Gere o documento de briefing completo agora.',
          watermark: 'Este briefing foi gerado pela Brieffy AI.'
        },
        en: {
          role: 'You are a Senior Brand Strategist and McKinsey-level consultant creating a premium Briefing Document.',
          langRule: `CRITICAL LANGUAGE CONSTRAINT: Write the ENTIRE document in ${targetLang}.`,
          task: 'TASK: Analyze the ENTIRE conversation below and produce a comprehensive, structured briefing document.',
          title: '📋 Strategic Briefing — [Company Name]',
          userMsg: 'Generate the complete briefing document now.',
          watermark: 'This briefing was generated by Brieffy AI.'
        },
        es: {
          role: 'Eres un Estratega de Marca Senior y consultor nivel McKinsey creando un Documento de Briefing premium.',
          langRule: `REGLA ABSOLUTA DE IDIOMA: Escribe el documento ENTERO en ${targetLang}.`,
          task: 'TAREA: Analiza TODA la conversación a continuación y produce un documento de briefing completo y estructurado.',
          title: '📋 Briefing Estratégico — [Nombre de la Empresa]',
          userMsg: 'Genera el documento de briefing completo ahora.',
          watermark: 'Este briefing fue generado por Brieffy AI.'
        }
    };
    const t = t_labels[chosenLanguage] || t_labels.pt;

    const formatInstructions = chosenLanguage === 'en'
      ? `OUTPUT FORMAT: Return the document as clean, semantic HTML. Use ONLY these tags:
- <h1> for the document title (one only)
- <h2> for main sections
- <h3> for subsections
- <p> for paragraphs
- <ul>/<li> for bullet lists, <ol>/<li> for numbered lists
- <blockquote> for important quotes, insights, or signal interpretations
- <strong> for bold emphasis, <em> for italic
- <hr> for section dividers
DO NOT use Markdown syntax (no #, *, -, > etc). Output pure HTML tags only.
DO NOT wrap the output in \`\`\`html code blocks. Return raw HTML directly.`
      : chosenLanguage === 'es'
      ? `FORMATO DE SALIDA: Devuelve el documento como HTML limpio y semántico. Usa SOLO estas etiquetas:
- <h1> para el título del documento (solo uno)
- <h2> para secciones principales
- <h3> para subsecciones
- <p> para párrafos
- <ul>/<li> para listas con viñetas, <ol>/<li> para listas numeradas
- <blockquote> para citas importantes, insights o interpretaciones de señales
- <strong> para énfasis en negrita, <em> para cursiva
- <hr> para divisores de sección
NO uses sintaxis Markdown (nada de #, *, -, > etc). Solo etiquetas HTML puras.
NO envuelvas la salida en bloques de código \`\`\`html. Devuelve HTML directamente.`
      : `FORMATO DE SAÍDA: Retorne o documento como HTML limpo e semântico. Use APENAS estas tags:
- <h1> para o título do documento (apenas um)
- <h2> para seções principais
- <h3> para subseções
- <p> para parágrafos
- <ul>/<li> para listas com marcadores, <ol>/<li> para listas numeradas
- <blockquote> para citações importantes, insights ou interpretações de sinais
- <strong> para ênfase em negrito, <em> para itálico
- <hr> para divisores de seção
NÃO use sintaxe Markdown (nada de #, *, -, > etc). Apenas tags HTML puras.
NÃO envolva a saída em blocos de código \`\`\`html. Retorne HTML diretamente.`;

    const systemPrompt = `${t.role}\n\n${t.langRule}\n\n${t.task}\n\nTEMPLATE: ${templateName}\n\nDATA:\n${JSON.stringify(briefingState, null, 2)}\n\nTRANSCRIPT:\n${conversationTranscript}\n\n${formatInstructions}\n\nRULES:\n- Write in ${targetLang}\n- Be extremely detailed\n- Professional agency-level tone\n- IT IS STRICTLY PROHIBITED TO USE EMOJIS ANYWHERE IN THE DOCUMENT.\n- ${t.watermark}`;

    // 3. Call LLM
    const res = await fetch(llmConfig.baseUrl, {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${llmConfig.apiKey}`,
        ...llmConfig.headers,
      },
      body: JSON.stringify({
        model: llmConfig.model,
        temperature: 0.3,
        max_tokens: 6000,
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: t.userMsg }
        ],
      }),
    });

    if (!res.ok) throw new Error(`LLM Error: ${res.status}`);
    const llmData = await res.json();
    let document = llmData.choices?.[0]?.message?.content;

    if (!document) throw new Error("No document content generated");

    // Strip possible ```html fencing if the LLM wraps it
    document = document.replace(/^```html\s*/i, '').replace(/\s*```$/i, '').trim();

    // 4. Update the Database — persist in both final_assets AND document_content
    const updatedFinalAssets = {
      ...assets,
      document: document,
      generated_at: new Date().toISOString()
    };

    const { error: updateError } = await supabase
      .from('briefing_sessions')
      .update({ 
        final_assets: updatedFinalAssets,
        document_content: document,
        updated_at: new Date().toISOString()
      })
      .eq('id', sessionId);

    if (updateError) throw updateError;

    return NextResponse.json({ success: true, document });

  } catch (error) {
    console.error("[SessionDocGen] Error:", error);
    return NextResponse.json({ error: error instanceof Error ? error.message : String(error) }, { status: 500 });
  }
}
